//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoRoofWorksWebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DomingoRoofWorksEntities : DbContext
    {
        public DomingoRoofWorksEntities()
            : base("name=DomingoRoofWorksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Job> Employee_Job { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Job_Material> Job_Material { get; set; }
        public virtual DbSet<Job_Type> Job_Type { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
    }
}
