//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoRoofWorksWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Job
    {
        public Employee_Job()
        {
            EmployeesJob_ID = "";
            Emp_ID = "";
            Job_Card_No = "";
        }

        public Employee_Job(string EmployeesJob_ID, string Emp_ID, string Job_Card_No)
        {
            this.EmployeesJob_ID = EmployeesJob_ID;
            this.Emp_ID = Emp_ID;
            this.Job_Card_No = Job_Card_No;
        }

        public string EmployeesJob_ID { get; set; }
        public string Emp_ID { get; set; }
        public string Job_Card_No { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
    }
}
